# Generated by Django 3.2.20 on 2024-04-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240408_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='our_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
