# Generated by Django 3.2.20 on 2024-04-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='our_rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
