# Generated by Django 3.2.20 on 2024-04-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
