# Generated by Django 3.2.20 on 2024-04-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.CharField(default=0, max_length=200, unique=True),
        ),
    ]
